spring:
  application:
    name: redis_cache

  datasource:
    url: jdbc:postgresql://localhost:5432/redis_cache
    username: pg
    password: pg

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
  server:
     port: 8089